# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-07 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceid', models.CharField(blank=True, default='instance id', max_length=255, null=True)),
                ('staticip', models.CharField(blank=True, default='static ip', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancetype', models.CharField(blank=True, default='instance type', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='user', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instancetype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instances.UserProfile'),
        ),
        migrations.AddField(
            model_name='instance',
            name='instancetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instances.InstanceType'),
        ),
        migrations.AddField(
            model_name='instance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instances.UserProfile'),
        ),
    ]
