# Generated by Django 2.1.2 on 2019-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='instancetype',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='type',
            field=models.CharField(blank=True, default='type', max_length=255, null=True),
        ),
    ]
