# Generated by Django 2.1.2 on 2019-01-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_auto_20190117_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='type',
            new_name='ins_type',
        ),
    ]
